#!/bin/bash

# Saga FinTech Dashboard - Quick Start Guide

echo "🚀 Starting Saga FinTech Dashboard..."
echo ""
echo "📋 Prerequisites:"
echo "  ✓ Node.js installed"
echo "  ✓ Backend server running on http://localhost:8080"
echo ""
echo "🔧 Installation:"
echo "  npm install       # Install dependencies (already done)"
echo ""
echo "▶️  Running the dashboard:"
echo "  npm start         # Start development server"
echo ""
echo "🏗️  Building for production:"
echo "  npm build         # Create optimized build"
echo ""
echo "📱 Available Routes:"
echo "  / .......................... Home/Landing page"
echo "  /dashboard ................ Main dashboard with stats"
echo "  /accounts ................ Account creation"
echo "  /transfer ................ Fund transfers"
echo "  /saga-dashboard .......... Saga monitoring"
echo ""
echo "🎨 Features:"
echo "  ✓ Professional dark theme"
echo "  ✓ Responsive design (mobile to desktop)"
echo "  ✓ Collapsible sidebar navigation"
echo "  ✓ User dropdown menu"
echo "  ✓ Real-time data loading"
echo "  ✓ Saga transaction monitoring"
echo "  ✓ Form validation"
echo "  ✓ Status indicators"
echo ""
echo "📖 Documentation:"
echo "  See DASHBOARD_SETUP.md for detailed information"
echo ""
echo "Ready to go! 🎉"
